name: continuous_calendar_example
description: "Example Flutter App for continuous_calendar."
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  continuous_calendar:
    path: ../
  date_n_time: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true