name: continuous_calendar
description: "An adaptable heatmap + picker calendar that diplays multiple months, perfect for booking."
version: 0.0.6
repository: https://github.com/CoalBuster/continuous_calendar

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  date_n_time: ^1.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
